
services:
  server:
    build: 
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - $HOME/data:/app/data
  qb:
    image: superng6/qbittorrentee:latest
    container_name: qb
    ports:
      - 8989:8989
      - 6881:6881
      - '6881:6881/udp'
    environment:
      PUID: 1000
      PGID: 100
      WEBUIPORT: 8989
    volumes:
      - $HOME/Downloads:/downloads
